plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.0.0'
}

group = 'net.terraimmerse'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url = 'https://jitpack.io'
    }
}

application {
    mainClass = 'net.terraimmerse.client.TerraImmerse'
}

project.ext.lwjglVersion = '3.4.2'
project.ext.jomlVersion = '1.10.9'
project.ext.lwjglNatives = 'natives-linux-arm32'

dependencies {

    // LWJGL
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-stb"

    // Raspberry Pi 3 ARM32 Natives
    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"

    // Libraries
    implementation "org.joml:joml:$jomlVersion"
    implementation "com.google.code.gson:gson:2.13.1"
    implementation "com.raylabz:opensimplex:1.0.3"

    // Tests
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
}

test {
    useJUnitPlatform()
}

// ==========================================
// Normale JAR
// ==========================================

jar {
    manifest {
        attributes(
            'Main-Class': 'net.terraimmerse.client.TerraImmerse'
        )
    }
}

// ==========================================
// Fat JAR / Uber JAR
// ==========================================

shadowJar {

    archiveBaseName = 'TerraImmerse'
    archiveVersion = project.version
    archiveClassifier = 'all'

    manifest {
        attributes(
            'Main-Class': 'net.terraimmerse.client.TerraImmerse'
        )
    }

    // Signaturdateien aus Dependencies entfernen
    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'

    // Service-Dateien zusammenführen
    mergeServiceFiles()
}