plugins {
    id 'java'
    id 'application'
    id 'com.gradleup.shadow' version '9.0.0'
}

group = 'net.terraimmerse'
version = 'classic-Pi-0.4.0'

application {
    mainClass = 'net.terraimmerse.client.TerraImmerse'
}

repositories {
    mavenCentral()
}

project.ext.lwjglVersion = "3.4.2"
project.ext.lwjglNatives = "natives-linux-arm32"
project.ext.jomlVersion = "1.10.9"

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")
    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.lwjgl:lwjgl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-stb::$lwjglNatives"
    implementation "org.joml:joml:$jomlVersion"
    implementation "com.google.code.gson:gson:2.13.1"
    implementation "com.raylabz:opensimplex:1.0.3"
}

shadowJar {
    archiveBaseName = "TerraImmerse-Pi"
    archiveVersion = version
    archiveClassifier = ""
    manifest {
        attributes(
            'Main-Class': application.mainClass.get()
        )
    }
}

def lwjglVersion = "3.4.2"

def nativeModules = [
    "lwjgl",
    "lwjgl-glfw",
    "lwjgl-opengl",
    "lwjgl-stb"
]

def nativePlatforms = [
    "linux-x64": "natives-linux",
    "linux-arm64": "natives-linux-arm64",
    "linux-arm32": "natives-linux-arm32",
    "linux-ppc64le": "natives-linux-ppc64le",
    "linux-riscv64": "natives-linux-riscv64",
    "macos-x64": "natives-macos",
    "macos-arm64": "natives-macos-arm64",
    "windows-x64": "natives-windows",
    "windows-x86": "natives-windows-x86",
    "windows-arm64": "natives-windows-arm64"
]

def nativeConfigurations = [:]
nativePlatforms.each { platformName, nativeClassifier ->
    def configurationName =
            "terraImmerse_${platformName.replaceAll("-", "_")}"

    nativeConfigurations[platformName] = configurations.create(configurationName)
    nativeModules.each { module ->
        dependencies.add(
            configurationName,
            "org.lwjgl:${module}:${lwjglVersion}:${nativeClassifier}"
        )
    }
}
